language: python

python: '3.6'

cache: pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

install:
  - pip install coveralls mypy

script:
  - coverage run run_tests.py
  - mypy graph/ test/

after_success:
  - coveralls
