language: python

python: '3.6'

cache: pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

install:
  - pip install coveralls mypy pytest-cov

script:
  - pytest -v --cov=graph test/
  - mypy --ignore-missing-imports graph/ test/

after_success:
  - coveralls
